#!/bin/bash



clear 

echo -e "\e[1;34m

▄▄▄█████▓ █    ██  ███▄    █  ███▄    █ ▓█████  ██▓    
▓  ██▒ ▓▒ ██  ▓██▒ ██ ▀█   █  ██ ▀█   █ ▓█   ▀ ▓██▒    
▒ ▓██░ ▒░▓██  ▒██░▓██  ▀█ ██▒▓██  ▀█ ██▒▒███   ▒██░    
░ ▓██▓ ░ ▓▓█  ░██░▓██▒  ▐▌██▒▓██▒  ▐▌██▒▒▓█  ▄ ▒██░    
  ▒██▒ ░ ▒▒█████▓ ▒██░   ▓██░▒██░   ▓██░░▒████▒░██████▒
  ▒ ░░   ░▒▓▒ ▒ ▒ ░ ▒░   ▒ ▒ ░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒░▓  ░
    ░    ░░▒░ ░ ░ ░ ░░   ░ ▒░░ ░░   ░ ▒░ ░ ░  ░░ ░ ▒  ░
  ░       ░░░ ░ ░    ░   ░ ░    ░   ░ ░    ░     ░ ░   
            ░              ░          ░    ░  ░    ░  ░
                  
            CREATED BY ARTURO
"



echo -e "\e[1;37m       "
echo -e "\e[1;31m       "
# Pedir al usuario que introduzca el puerto que desean utilizar
echo "Introduce el puerto que deseas utilizar
o que esta indicado en su localhost : "

echo -e "\e[1;37m       "
read   PUERTO 

# Ejecutar el comando cloudflared tunnel con el puerto especificado
cloudflared tunnel --url 127.0.0.1:$PUERTO 2>&1 


# Buscar enlaces de Cloudflare que terminen en "trycloudflare.com"
cloudflare_link=$(curl -s https://www.cloudflare.com/apps/ | grep -o 'https://[-0-9a-z]*\.trycloudflare.com')

# Imprimir el enlace encontrado
echo $cloudflare_link 
